# Generated by Django 4.2.27 on 2026-09-27 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rules', models.JSONField(default=list, help_text='Entry conditions; each item names an indicator, condition, and value.')),
                ('logic', models.CharField(choices=[('AND', 'All conditions must match'), ('OR', 'Any condition may match')], default='AND', max_length=3)),
                ('exit_rules', models.JSONField(default=list, help_text='Exit conditions evaluated independently from entry conditions.')),
                ('exit_logic', models.CharField(choices=[('AND', 'All conditions must match'), ('OR', 'Any condition may match')], default='OR', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='strategy',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_strategy_name_per_user'),
        ),
    ]
