# Generated by Django 4.2.27 on 2026-09-27 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instruments', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.JSONField(help_text='Inclusive start and end dates in ISO format.')),
                ('interval', models.CharField(choices=[('1m', '1 minute'), ('5m', '5 minutes'), ('1d', '1 day')], default='1d', max_length=2)),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backtest_runs', to='instruments.instrument')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_runs', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='backtest_runs', to='strategies.strategy')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', 'status'], name='backtest_user_status_idx')],
            },
        ),
    ]
