# Generated by Django 4.2.27 on 2026-09-27 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('condition', models.JSONField(blank=True, default=dict, help_text='Rule set used when strategy is not supplied.')),
                ('interval', models.CharField(choices=[('1m', '1 minute'), ('5m', '5 minutes'), ('1d', '1 day')], default='1d', max_length=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notification_channel', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook')], default='email', max_length=10)),
                ('webhook_url', models.URLField(blank=True)),
                ('cooldown_minutes', models.PositiveSmallIntegerField(default=5)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='instruments.instrument')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='strategies.strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertTriggerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('condition_results', models.JSONField(default=dict)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('delivery_error', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_logs', to='alerts.alert')),
            ],
            options={
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['alert', 'triggered_at'], name='alert_log_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active', 'instrument'], name='alert_active_instr_idx'),
        ),
    ]
